version: '3.4'
services:
  typemill:
    container_name: typemill
    restart: always
    image: bluffy2006/typemill:latest
    volumes:
      - ./data/settings:/var/www/html/settings
      - ./data/cache/:/var/www/html/cache/ 
      - ./data/content/:/var/www/html/content/ 
      - ./data/media/:/var/www/html/media/ 
      #- ./data/themes/:/var/www/html/themes/ 
      - ./data/plugins/:/var/www/html/plugins/ 
    ports:
      - '9080:80'     
    environment:
      - TYPEMILL_UID=1000
      - TYPEMILL_GID=1000  